POST http://localhost:3001/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OTY3NGQzOGM5MWI1MjgxZTFhOTAyMWYiLCJlbWFpbCI6InBia2FyYW45OTlAZ21haWwuY29tIiwiaWF0IjoxNzY4MzgwNzI2LCJleHAiOjE3Njg0NjcxMjZ9.w6Gf9L_MUo07sjhcHhsZdjMs-lzSfWmJpGMQf8NAJSI
{
  "title": "Task is Task 3",
  "dueDate": "2025-01-01T12:00:00Z",
  "description": "Do whatever you want.",
  "priority": "normal",
  "period": "yearly",
  "status": "todo",
  "extraField": "This field should be ignored"
}